### ISSUE TITLE
gmf.BackgroundlayerselectorController is broken

### ISSUE THREAD

**Issue by tsauerwein** [camptocamp/ngeo#1791]
Locally I get the following error when trying to open all three applications (mobile, desktop, desktop_alt):

```
AssertionError: Assertion failed: The dimensions object is required
    at new goog.asserts.AssertionError (http://localhost:3000/@/home/tsauerwein/projects/ngeo/node_modules/closure-…9481f1e57fbba986e2304ac80d4173f94c9c/closure/goog/asserts/asserts.js:62:20)
    at Object.goog.asserts.doAssertFailure_ (http://localhost:3000/@/home/tsauerwein/projects/ngeo/node_modules/closure-…481f1e57fbba986e2304ac80d4173f94c9c/closure/goog/asserts/asserts.js:121:11)
    at Object.goog.asserts.assert [as assert] (http://localhost:3000/@/home/tsauerwein/projects/ngeo/node_modules/closure-…481f1e57fbba986e2304ac80d4173f94c9c/closure/goog/asserts/asserts.js:151:18)
    at new gmf.BackgroundlayerselectorController (http://localhost:3000/@/home/tsauerwein/projects/ngeo/contribs/gmf/src/directives/backgroundlayerselector.js:129:16)
    at Object.invoke (http://localhost:3000/node_modules/angular/angular.js:4718:19)
    at $controllerInit (http://localhost:3000/node_modules/angular/angular.js:10354:34)
    at nodeLinkFn (http://localhost:3000/node_modules/angular/angular.js:9263:34)
    at http://localhost:3000/node_modules/angular/angular.js:9673:13
    at processQueue (http://localhost:3000/node_modules/angular/angular.js:16383:28)
    at http://localhost:3000/node_modules/angular/angular.js:16399:27
```

On the online demo, I only see this error for `mobile` and `desktop`.

**Comment by adube** [comment]
Caused by #1701.  I'll read about it and figure out what's missing.

**Comment by gberaudo** [comment]
You need to pass the `dimensions` object from the main controller to the directive.
