### ISSUE TITLE
make apidoc is broken

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#2181]
Related to es6 support, the apidoc target is broken

```
/home/fgravin/dev/ngeo/jsdoc/get-angularjs-doc-ref.js:1
(function (exports, require, module, __filename, __dirname) { let https = require("https");
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Adding `"use strict";` to `jsdocAngularJS.js` and `.build/jsdocOl3.js`, but still get

```
FATAL: Unable to load template: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
make: *** [.build/apidoc] Error 1
```

**Comment by gberaudo** [comment]
Fixed by https://github.com/camptocamp/ngeo/pull/2182.
