### ISSUE TITLE
Styling and mapfish-print / geotools issue

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/ngeo#3060]
Currently the ngeo styles are generated to look this way: `_ngeo_style_${id1}: id2`. This breaks geotools when a feature `properties` does not contain all the keys of the available styles:

```
print_1          | 11:01:31.769 [ForkJoinPool-2-worker-38] ERROR org.geotools.rendering - Could not find '_ngeo_style_1' in the FeatureType (http://www.opengis.net/gml:GeosjonFeatureType), available attributes are: [_ngeo_style_0, geometry]
print_1          | org.geotools.filter.IllegalFilterException: Could not find '_ngeo_style_1' in the FeatureType (http://www.opengis.net/gml:GeosjonFeatureType), available attributes are: [_ngeo_style_0, geometry]
print_1          |      at org.geotools.renderer.lite.StreamingRenderer.checkAttributeExistence(StreamingRenderer.java:2077)
print_1          |      at org.geotools.renderer.lite.StreamingRenderer.getFeatures(StreamingRenderer.java:1991)
print_1          |      at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:1899)
print_1          |      at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:821)
print_1          |      at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:602)
print_1          |      at org.mapfish.print.map.geotools.AbstractGeotoolsLayer.render(AbstractGeotoolsLayer.java:115)
print_1          |      at org.mapfish.print.processor.map.CreateMapProcessor.createLayerGraphics(CreateMapProcessor.java:303)
print_1          |      at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:135)
print_1          |      at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:103)
print_1          |      at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:200)
```

An improvement would be to:
- use a single "namespace":  `_ngeo_style` (no counter);
- have an array of symbolizers per style instead of an array of styles of 1 symbolizer.

**Comment by gberaudo** [comment]
Discussed with @sbrunner, the issue was due to a single OL style used for different kind of geometries.
We need to take into account of geometry type when creating/caching the symbolizers.

**Comment by sbrunner** [comment]
https://jira.camptocamp.com/browse/GSGMF-552
