### ISSUE TITLE
Build failed with Node 0.10.21 and npm 1.4.21

### ISSUE THREAD

**Issue by sbrunner** [camptocamp/ngeo#433]
related to https://github.com/camptocamp/ngeo/issues/424#issuecomment-161630517

**Comment by sbrunner** [comment]
The errors I have:
```
npm install --force
npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json demo@0.0.1 No repository field.
 
> utf-8-validate@1.2.1 install /var/www/vhosts/geomapfish-demo/private/master/node_modules/openlayers/node_modules/closure-util/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make[1]: Entering directory '/var/www/vhosts/geomapfish-demo/private/master/node_modules/openlayers/node_modules/closure-util/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
validation.target.mk:86: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make[1]: *** [Release/obj.target/validation/src/validation.o] Error 1
make[1]: Leaving directory '/var/www/vhosts/geomapfish-demo/private/master/node_modules/openlayers/node_modules/closure-util/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/vhosts/geomapfish-demo/private/master/node_modules/openlayers/node_modules/closure-util/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by sbrunner** [comment]
For me the suspect commit is: https://github.com/openlayers/ol3/commit/3f30072de54ee3667a45fdc8c6ffda3d80e14fcd

**Comment by fredj** [comment]
See https://github.com/nodejs/nan/issues/414
