### ISSUE TITLE
Can't make apidoc

### ISSUE THREAD

**Issue by fgravin** [camptocamp/ngeo#924]
```
    jsdocOl3.registerOl3Link(helper);
             ^

TypeError: jsdocOl3.registerOl3Link is not a function
    at Object.exports.publish (/home/fgravin/dev/ngeo/jsdoc/template/publish.js:445:14)
    at Object.module.exports.cli.generateDocs (/home/fgravin/dev/ngeo/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/home/fgravin/dev/ngeo/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/home/fgravin/dev/ngeo/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/home/fgravin/dev/ngeo/node_modules/jsdoc/cli.js:180:5)
```

Am I alone ?
Is it related to recent ol3 changes ?

**Comment by fgravin** [comment]
My `jsdocOl3.js` file was empty.
A `make cleanall` solved it.
